version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: prakticum-pgdb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4
    container_name: prakticum-pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '${PGADMIN_PORT}:80'
    volumes:
      - ./tmp/padmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

  server:
    container_name: prakticum-server
    image: prackicum-server
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - awesome

  nginx:
    container_name: prakticum-nginx
    image: nginx
    environment:
      PUBLIC_HOST: coder-32.ya-praktikum.tech
      SERVER_PORT: 3001
    volumes:
      # конфиг уже на сервере.
      - /coder/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # сертификаты уже на сервере.
      - /certbot/www:/var/www/certbot/:ro
      - /certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - awesome

networks:
  awesome:
